version: '3'
networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        SQL_DATABASE: $SQL_DATABASE
        SQL_ROOT_PASSWORD: $SQL_ROOT_PASSWORD
        SQL_ADMIN: $SQL_ADMIN
        SQL_ADMINPASSWD: $SQL_ADMINPASSWD
        SQL_USER: $SQL_USER
        SQL_USERPASSWD: $SQL_USERPASSWD
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/lciullo/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/lciullo/data/mariadb
